### PR TITLE
Batteries included akka-http sangria library

### PR DESCRIPTION
**Pull request by anzecesar**
This is a history preserving morph of the [akka http sangria example](https://github.com/sangria-graphql/sangria-akka-http-example).

Still on TODO:
- [ ] Clean up
- [ ] Add tests
- [ ] Improve readme
- [ ] Add what is needed (versioning, other settings) to publish & publish
- [ ] Refactor the http example to use this lib

### CODE REVIEW

**Comment by nickhudkins** [comment]
Super super nitpicky, but before we merge this, let's squash the crap out of these commits, especially as it's the initial implementation.

Honestly, this looks solid, I'd be happy to go down this path once we have tests :). Let me know if you want a hand or would like to talk through what we plan to support.

Happy to help write some documentation if we need as well. I can work on getting permissions so once we merge, we can get a release published! This is super exciting!

**Comment by anzecesar** [comment]
@nickhudkins Sure, it can also be done with a squash merge :).

I have adding tests on my todo, will try to find time by the end of week for it.

I would not add scope to the initial PR. Just tests. We can discuss the next steps though.

**Comment by nickhudkins** [comment]
Hey @anzecesar pardon the delay on this.

Sorry for the lack of direction around the tests. Since the boundaries of the code here are really JUST taking `akka-http` request and transforming it to a known format to reduce boilerplate, I think the tests can be pretty minimal and should NOT include any schema or anything of that nature.

With the following test cases...

```
HTTP GET => 
	  QueryString:	query
	  QueryString:	query, operationName
	  QueryString:	query, variables
	  QueryString:	query, operationName, variables


HTTP POST (application/json) => 
	  Body: { query }
	  Body: { query, operationName }
	  Body: { query, variables }
	  Body: { query, operationName, variables }


HTTP POST (application/graphql)
	Body: GraphQL Literal
	Body: GraphQL Literal, QueryString: operationName 
	Body: GraphQL Literal, QueryString: variables
	Body: GraphQL Literal, QueryString: operationName, variables
```

**Comment by nickhudkins** [comment]
I had some time to work on this so I have pushed up a commit that provides some tests that are not reliant on a schema, in an attempt to make them more `unit`-like. 

In addition, I ran into many interesting parsing concerns that I wanted to make sure behaved in a consistent manner. As you can see there are some TODOs left behind. Mostly I'd like to provide solid assertion messages that would help future me, or anyone else who may break tests in the future :)

I also stuck `scalafmt` in there so that I can not think about formatting. We've begun moving this way across all of the repos here in the sangria-graphql org.

**Comment by anzecesar** [comment]
Scalafmt and helpful error and asserion messages are all great ideas :).

While doing the tests I was thinking that the abstraction in here is too leaky at the highest, most out of the box, case: 

`prepareGraphQLRequest` takes `PartialFunction[Try[GraphQLRequest[T]], StandardRoute]`, which in turn means the user still needs to handle a bunch of http boilerplate such as marshalling the errors, etc. Put differently, it feels like mixing GraphQL domain with http (input is from GraphQL domain, output is from http domain).

I was looking for ways of moving this in to the library, but `Executor.execute` returns `scheme.Result[Ctx, marshaller.Node]`, which is dependent on the schema.  While we could add `GrphQLResponse`, I feel like that's just adding another very short lived object for the GC to clean up.

Looking over to popular libraries in other languages, it would be awesome if bootstrapping with Sangria would also be as simple as 
```
  route = yourExistingRoutes ~ graphql(minimal wiring)
```
if you need more control, you can always implement around the lower level building blocks.
wdyt?

**Comment by nickhudkins** [comment]
@anzecesar I am relatively unconvinced that Sangria itself has much boilerplate to get going, as a minimal example can be found below:

```scala
import sangria.schema._
import sangria.execution._
import sangria.macros._
import sangria.marshalling.circe._
import scala.concurrent.ExecutionContext.Implicits.global

val QueryType = ObjectType("Query", fields[Unit, Unit](
  Field("hello", StringType, resolve = _ => "Hello world!")
))

val schema = Schema(QueryType)

val query = graphql"{ hello }"

val result = Executor.execute(schema, query)

result.foreach(res => println(res.spaces2))
```

My first pass at making sangria-akka-http-example simpler was to hide `Executor.execute` entirely, but found that you gave up flexibility for the sake of getting started quickly.

Instead I decided to attempt to hide the crap specific to handling an HTTP request as it relates to an incoming HTTP request intended for a GraphQL server.

The scope shrunk to focus specifically to focus ONLY on:

**Encapsulate the common GraphQL HTTP Request formats**
- GET (query, variables, operationName) [Queries Only]
- POST `application/json` ({ query, variables, operationName }) [Most Common Use]
- POST `application/graphql` (GraphQL Document as body, variables, operationName)

The thing that remains something I'd like to address is absolutely error handling:

```scala
case Success(parsedReq) =>
	  /* ... */
	  val resp = Executor.execute(/* ... */).map(OK -> _)
	   .recover {
		 /* Execution errors */ 
	     case error: QueryAnalysisError => BadRequest -> error.resolveError
	     case error: ErrorWithResolver => InternalServerError -> error.resolveError
	   }
case Failure(err) =>
	/* Query Preparation Error */
```

Currently `execute` expects two things that could fail earlier than `.execute`:
 - a parsed GraphQL document 
 - variables that conform to the `Input` type (have a ToInput implicit in scope)

💡 We could create a variant of `Executor.execute` that accepts a byte-string (for the query, and variables) or something and move the query AST parsing, and variable marshalling into `Executor`. This at least allows for centralized error handling.

What I would say is.. we can absolutely wrap the partial function up one more time if we need to provide an even simpler API for folks, but anything beyond that I believe begins talking about where does the responsibility of `sangria` stop and end.

Let's make sure we're not making perfect the enemy of good enough, since we can keep releasing versions if we land somewhere that is even better. Assuming that we're reducing boilerplate for folks to write, even if we were to introduce a breaking change to the `sangria-akka-http` library, the surface area of code required to change would be small.

Hope this helps explain where my head is at on this!

**Comment by nickhudkins** [comment]
For context... with what we have, we could "wrap it up" so that one only would need to provide a schema:

The below is... sloppy, but hopefully illustrates the point a little bit.

```  
def graphqlHandler[Ctx, Root, Input](schema: Schema[Ctx, Root])(
    implicit executionContext: ExecutionContext,
    marshaller: ResultMarshaller,
    um: InputUnmarshaller[Input],
    rm: ToEntityMarshaller[(StatusCode, ResultMarshaller#Node)],
    reqUm: FromRequestUnmarshaller[GraphQLHttpRequest[Input]],
    varUm: FromStringUnmarshaller[Input],
    v: Variables[Input],
    justError: ToEntityMarshaller[GraphQLError],
    errorUm: ToEntityMarshaller[GraphQLErrorResponse]): Route =
    graphQLRoute[Input] {
      case Success(req) =>
        val resp = Executor.execute[Ctx, Root, Input](
          schema = schema,
          queryAst = req.query,
          variables = req.variables,
          operationName = req.operationName
        ).map(OK -> _)
          .recover {
            case error: QueryAnalysisError => BadRequest -> error.resolveError
            case error: ErrorWithResolver => InternalServerError -> error.resolveError
          }
        complete(resp)
      case Failure(preparationError) =>
        complete(BadRequest, formatError(preparationError))
    }
    ```

**Comment by anzecesar** [comment]
@nickhudkins 

Yeah I wasn't saying Sangria has a lot of boilerplate, but that this lib should be magical to start with :). And yes, that error handling made it mix sangria with akka http in a way that kind of requires you (the user) to still write some unneccessary boiler plate. 

And to be clear, it was good enough even without your latest commit. Done is better than perfect. I was just thinking out loud, should've been more clear about it being a nice to have as opposed to must have. 

Thank you for all the commits. Sorry I don't have much time for this - we have quite a crunch at work at the moment and layered on top is all this covid mess, so I kind of have to drop some balls :/.

**Comment by nickhudkins** [comment]
No worries @anzecesar ! I happen to have a project kicking off that I am hoping to pull some of this stuff in for. I'll go ahead and cut a release of this to get it out there, and hopefully we can keep working together to make it even better 👍

**Pull request merged**
